/*! @wlxm/react-model - v0.1.1 - 4/5/2020 https://niannings.github.io */
!function(e,r){"object"==typeof exports&&"undefined"!=typeof module?r(exports,require("react")):"function"==typeof define&&define.amd?define(["exports","react"],r):r((e=e||self).reactModel={},e.React)}(this,(function(e,r){"use strict";var n="default"in r?r.default:r,t=function(){return(t=Object.assign||function(e){for(var r,n=1,t=arguments.length;n<t;n++)for(var o in r=arguments[n])Object.prototype.hasOwnProperty.call(r,o)&&(e[o]=r[o]);return e}).apply(this,arguments)};
/*! *****************************************************************************
    Copyright (c) Microsoft Corporation. All rights reserved.
    Licensed under the Apache License, Version 2.0 (the "License"); you may not use
    this file except in compliance with the License. You may obtain a copy of the
    License at http://www.apache.org/licenses/LICENSE-2.0

    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
    WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
    MERCHANTABLITY OR NON-INFRINGEMENT.

    See the Apache Version 2.0 License for specific language governing permissions
    and limitations under the License.
    ***************************************************************************** */function o(){for(var e=0,r=0,n=arguments.length;r<n;r++)e+=arguments[r].length;var t=Array(e),o=0;for(r=0;r<n;r++)for(var u=arguments[r],i=0,a=u.length;i<a;i++,o++)t[o]=u[i];return t}var u=function(e){return e.replace(/\[([^\[\]]*)\]/g,".$1.").split(".").filter((function(e){return""!==e}))},i=function(e){for(var r=[],n=1;n<arguments.length;n++)r[n-1]=arguments[n];return o(r).map((function(r){return u(r).reduce((function(e,r){return null==e?void 0:e[r]}),e)}))};function a(e,r){return t(t({},e),r)}function l(e,n){return r.useReducer(a,e,n)}var f=Date.now();function c(e){for(var r=e._owner;r;){var n=r.pendingProps["$model-id"];if(n)return n;r=r.return}throw new Error("useModel只能在withModel高阶组件下使用～")}var d=new Map;function v(e){var n=e.value,t=e.key,o=e.validators,u=void 0===o?[]:o,i=e.setError,a=e.setModel;return r.useEffect((function(){for(var e,r,o=-1,l=u.length;++o<l;){var f=u[o](n,(function(e){var r;return a(((r={})[t]=e,r))}));if(f){i(((e={})[t]=f,e));break}}o===l&&i(((r={})[t]=void 0,r))}),[n]),null}e.useBothWayBinding=function(e){var n=c(e),t=d.get(n);return function e(n,t,u){return n?r.Children.map(n,(function(n){var a=i(n,"props._modelname")[0];if(a)return function(e){var n=e.jsxEl,t=e.model,u=e.setModel,a=e.modelName,l=i(n,"props")[0]||{},f=l._prop,c=void 0===f?"value":f,d=l._event,v=void 0===d?"onChange":d,s=l._byevent,p=void 0!==s&&s,m=l._deps,g=void 0===m?[]:m,h=i(t,a)[0],y=o([h],g),M=r.useRef((function(e){var r;u(((r={})[a]=p?e.target[c]:e,r))}));return g.length,r.useMemo((function(){var e;return r.cloneElement(n,((e={})[c]=h||("input"===n.type?"":h),e[v]=M.current,e))}),y)}({jsxEl:n,model:t,setModel:u,modelName:a});var l=i(n,"props.children")[0];return l?r.cloneElement(n,{children:e(l,t,u)}):n})):n}(e,t[0],t[1])},e.useModel=function(e){void 0===e&&(e={});var t=n.createElement(n.Fragment,null),o=c(t),i=d.get(o)||[],a=i[0],f=i[1],v=l(e),s=v[0],p=v[1];r.useEffect((function(){return function(){o===t._owner["$model-id"]&&d.delete(o)}}),[]);var m=r.useCallback((function(e){var r=Object.keys(e)[0];!function(e,r,n){var t=u(r),o=t.length-1;t.reduce((function(e,r,u){return u===o?(e[r]=n,e):(e[r]||(/^\d+$/.test(t[u+1])?e[r]=[]:e[r]={}),e[r])}),e)}(s,r,e[r]),f?f(s):p(s)}),[]);return a||d.set(o,[s,m]),d.get(o)},e.useModelValidator=function(e,r){var n=e[0],t=e[1];void 0===r&&(r={});for(var o=l({}),u=o[0],a=o[1],f=Object.keys(r),c=f.length;--c>-1;){var d=f[c];v({value:i(n,d)[0],key:d,validators:r[d],setError:a,setModel:t})}return u},e.withModel=function(e){var r;++f;var o=((r={})["$model-id"]=f.toString(32),r);return function(r){return n.createElement(e,t({},r,o))}},Object.defineProperty(e,"__esModule",{value:!0})}));
